# Config file for Diddy Kong Racing NTSC 1.0 Recompilation.

[input]
entrypoint = 0x80000400
# Paths are relative to the location of this config file.
output_func_path = "RecompiledFuncs"
#relocatable_sections_path = "overlays.us.rev1.txt"
elf_path = "dkr.elf"
rom_file_path = "dkr.z64"
#trace_mode = true

manual_funcs = [
    { name = "__amMan", section = ".main", vram = 0x80002A98, size = 360 },
    { name = "__amDmaNew", section = ".main", vram = 0x80003008, size = 56 },
    { name = "__scSchedule", section = ".main", vram = 0x8007A0D4, size = 504 },
    { name = "__scMain", section = ".main", vram = 0x800795AC, size = 436 }
]

[patches]
function_sizes = [
    { name = "gzip_inflate_block", size = 260 }
]

stubs = [
    # Stub out unused functions that directly manipulate RCP status.
    #"RcpUtils_PrintRegisterStatus",
    #"RcpUtils_Reset",
    # Stub out an unnecessary function that accesses kseg1 addresses.
    #"CIC6105_Init"
    # Stub out debugging function set_breakpoint (?)
    "set_breakpoint"
]

ignored = [
    # Not actually a function
    #"D_80186028"
    "osPfsReFormat",
    "__osBlockSum"
]

renamed = [
    "main",
    "_itoa"
]

# Single-instruction patches

# Disable check_imem_validity
[[patches.instruction]]
func = "check_imem_validity"
vram = 0x8006F4F0
value = 0x00000000

[[patches.instruction]]
func = "check_imem_validity"
vram = 0x8006F4F8
value = 0x00000000

# Disable check_dmem_validity
[[patches.instruction]]
func = "check_dmem_validity"
vram = 0x8006EFBC
value = 0x00000000

[[patches.instruction]]
func = "check_dmem_validity"
vram = 0x8006EFC4
value = 0x00000000
